# S03 T04: Pràctica amb programació numèrica

## Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [22]:
import numpy as np

vec = np.array([(10, 20, 30, 40, 50, 60, 70, 80, 90, 100), (10, 20, 30, 40, 50, 60, 70, 80, 90, 100)])

# print(vec.ndim)

def resum(array):
    if array.ndim > 1:
        print("ERROR: el array introuït té més d'una dimensió")
    else:
        print("La suma dels elements del array és: ", array.sum(), "\n",
              "El minim dels elements del array és: ", array.min(), "\n",
              "El major valor dels elements del array és: ", array.max(), "\n",
              "La mitjana (mean) dels elements del array és: ", array.mean(), "\n",
#              "La suma total dels elements del array és: ", array.cumsum(axis=0), "\n",
#              "La mitjana (median) dels elements del array és: ", array.median(), "\n",
#              "El coeficient de correlació dels elements del array és: ", array.corrcoef(), "\n",
#              "La desviació estàndard  dels elements del array és: ", array.std(b), "\n",
             )
resum(vec)

        

2
ERROR: el array introuït té més d'una dimensió


## Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [15]:
from numpy import random

def ranMat(num):
    mat = random.randint(100, size = (num, num))
    return mat


num1 = int(input("Introdueix la mida de la matriu: "))
mat = ranMat(num1)
print(mat)


Introdueix un nom nombre senser: 7
[[82 46 78 61 96 18 35]
 [ 5 41 18 35 41 75 92]
 [34  2 63 67 76 18 52]
 [23 37 54 86 56 68 85]
 [86 24 35 77 35 85 16]
 [84 20  0 21 71 99 10]
 [ 6 47 46 46 42 27 94]]


## Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [28]:
def sumTot(array):
    if array.ndim == 2:
        rowTot = np.sum(array, axis=1)
        colTot = np.sum(array, axis=0)
        return (rowTot, colTot)
    else:
        print("La taula introduïda no té dues dimensios. Si us plau reviseu-la")
        
sumMat = sumTot(mat)

print("La suma de les files de la taula és: ", sumMat[0])
print("La suma de les columnes de la taula és: ", sumMat[1])

La suma de les files de la taula és:  [416 307 312 409 358 305 308]
La suma de les columnes de la taula és:  [320 217 294 393 417 390 384]


## Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [43]:
# sources: 
# https://en.wikipedia.org/wiki/Correlation_coefficient
# https://en.wikipedia.org/wiki/Pearson_correlation_coefficient
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html
# https://realpython.com/numpy-scipy-pandas-correlation-python/#example-numpy-correlation-calculation

# Coeficient de correlació per a dos vectors (arrays d'una dimensió)
def corCoef(x,y):
    if x.ndim == 1 and y.ndim == 1:
        num = np.sum((x-np.mean(x))*(y-np.mean(y)))
        den = np.sqrt(np.sum((x-np.mean(x))**2) * np.sum((y-np.mean(y))**2))
        return (num/den)
    else:
        print("Error: algun dels arrays introduïts no té només una dimensió.")


In [57]:
import scipy.stats

# Misura el
x = sumMat[0]
y = sumMat[1]

print(corCoef(x,y))

# comparar amb metodes de altres libreries
print(np.corrcoef(x, y)[1][0])

print(scipy.stats.pearsonr(x, y)[0])

0.2599283164032047
0.25992831640320463
0.2599283164032047
